spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 2
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20
      validation-query: SELECT 'x'
      validation-query-timeout: 30000
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000;druid.stat.logSlowSql=false
      use-global-data-source-stat: true
      reset-stat-enable: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: Abc_.123
        allow: 127.0.0.1,192.168.0.0/16
      #        deny: localhost
      aop-patterns: com..*.service.impl.*Impl.*(..)
      web-stat-filter:
        url-pattern: /*
        exclusions: '*.css,*.js,*.ico,*.png,*.jpg,*.gif,/druid/*'
        profile-enable: true
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #设置空如何序列化
    default-property-inclusion: non_null
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: true
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: true
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true



mybatis:
  type-aliases-package: com.**.analysis.pojo
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    lazy-loading-enabled: true
    default-enum-type-handler: com.tj.bigdata.analysis.ibatis.EnumTypeHandler
  lazy-initialization: true
mapper:
  identity: mysql
  not-empty: false
  mappers:
    - tk.mybatis.mapper.common.MySqlMapper
    - tk.mybatis.mapper.common.IdsMapper
    - tk.mybatis.mapper.common.Mapper
  safe-delete: true
  safe-update: true
pagehelper:
  helper-dialect: mysql
  #offset-as-page-num: true
  #row-bounds-with-count: true
  #page-size-zero: true
  reasonable: false
  support-methods-arguments: true
  params: count==countSql
  default-count: false